#开发环境配置
server:
  # 服务端口
  port: 5000


spring:
  application:
    name: latticy-cms
  # 数据源配置，请修改为你项目的实际配置
  datasource:
    username: root
    password: Mysql8.0
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sleeve?useSSL=false&serverTimezone=UTC&characterEncoding=UTF8&allowPublicKeyRetrieval=true


# 开启权限拦截
auth:
  enabled: true

# 开启登录要求验证码
login-captcha:
  enabled: false
  secret: "m49CPM5ak@MDXTzbbT_ZEyMM3KBsBn!h"

# 开启http请求日志记录
request-log:
  enabled: true


logging:
  level:
    # web信息日志记录
    web: debug
    # SQL日志记录
    io.github.talelin.latticy.mapper: debug

####暴露端点给Prometheus采集 [必须] - START ####
management:
  endpoints:
    web:
      exposure:
        # 暴露端口：metrics，其中就包含我们需要的JVM相关指标
        # 需要暴露的端点：[health,info,metrics]用,分隔
        include: info,metrics,prometheus
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        pushgateway:
          # 启用推送 如果不需要设置为false
          enabled: true
          username: admin
          password: SN#dljy.13579
          # PUSHGATEWAY 地址
          baseUrl: 192.168.191.15:29091
          # 推送周期 每隔15秒上报一次
          pushRate: 15s
          # job定义名
          job : ${spring.application.name}
#### 暴露端点给Prometheus采集 [必须] - END ####